site_name: DADA-Forest
site_dir: public
nav:
  - Home: index.md
  - 'Test Plan': test-plan.md
  - 'Catalog and Inventory': catalog.md
  - 'Existing Infrastrcture and Connections': connections.md
  - 'R & D and Testing': r-and-d-test.md
theme: readthedocs
markdown_extensions:
  - attr_list
  - tables